inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - '**/Gemfile'

Style/Encoding:
  Enabled: true

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/IndentHash:
  EnforcedStyle: consistent

Style/MethodCalledOnDoEndBlock:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Lint/EndAlignment:
  AlignWith: variable
